# Send-NewsDigestEmail.ps1
# 发送新闻简报邮件通知

param(
    [Parameter(Mandatory=$true)]
    [string]$Date,
    
    [Parameter(Mandatory=$true)]
    [string]$HtmlUrl,
    
    [string]$To = "zizaiqizizhangxiqi@qq.com",
    [string]$From = "zizaiqizizhangxiqi@qq.com",
    [string]$SmtpServer = "smtp.qq.com",
    [int]$SmtpPort = 587,
    [string]$Username = "zizaiqizizhangxiqi@qq.com",
    [string]$Password = "akgxxrbxcfkeiaec"
)

$subject = "📰 News Digest - $Date"

$body = @"
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: linear-gradient(135deg, #1e3c72 0%, #2a5298 100%); color: white; padding: 30px; text-align: center; border-radius: 12px 12px 0 0; }
        .header h1 { margin: 0; font-size: 1.8em; }
        .content { background: #f8f9fa; padding: 30px; border-radius: 0 0 12px 12px; }
        .link-box { background: white; padding: 20px; border-radius: 8px; text-align: center; margin: 20px 0; }
        .link-box a { color: #667eea; text-decoration: none; font-size: 1.1em; font-weight: 600; }
        .link-box a:hover { text-decoration: underline; }
        .footer { text-align: center; color: #666; margin-top: 20px; font-size: 0.9em; }
    </style>
</head>
<body>
    <div class="header">
        <h1>📰 Morning News Digest</h1>
        <p>$Date</p>
    </div>
    <div class="content">
        <p>你的今日新闻简报已生成并推送到 GitHub。</p>
        
        <div class="link-box">
            <a href="$HtmlUrl" target="_blank">点击查看简报 →</a>
        </div>
        
        <p>简报包含：</p>
        <ul>
            <li>经济新闻</li>
            <li>地缘政治新闻</li>
            <li>每日词汇测验</li>
        </ul>
    </div>
    <div class="footer">
        <p>Generated by 小宇宙 🪐</p>
        <p><a href="https://github.com/zizaiqizi/newsDigestByXiaoYu">View on GitHub</a></p>
    </div>
</body>
</html>
"@

try {
    $securePassword = ConvertTo-SecureString $Password -AsPlainText -Force
    $credential = New-Object System.Management.Automation.PSCredential($Username, $securePassword)
    
    # 使用 Send-MailMessage (PowerShell 5.1+)
    Send-MailMessage `
        -From $From `
        -To $To `
        -Subject $subject `
        -Body $body `
        -BodyAsHtml `
        -SmtpServer $SmtpServer `
        -Port $SmtpPort `
        -UseSsl `
        -Credential $credential `
        -Encoding UTF8
    
    Write-Host "✅ Email sent successfully to $To" -ForegroundColor Green
}
catch {
    Write-Host "❌ Failed to send email: $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}
