# Send-NewsDigestEmail.ps1
# Send news digest email notification - SECURE VERSION

param(
    [Parameter(Mandatory=$true)]
    [string]$Date,
    [Parameter(Mandatory=$true)]
    [string]$HtmlUrl,
    [string]$To = "zizaiqizizhangxiqi@qq.com",
    [string]$From = "zizaiqizizhangxiqi@qq.com",
    [string]$SmtpServer = "smtp.qq.com",
    [int]$SmtpPort = 587,
    [string]$Username = "zizaiqizizhangxiqi@qq.com"
)

# Load password from secure storage
$SecretsFile = "$env:USERPROFILE\.openclaw\.secrets.json"
$Password = $null

try {
    if (Test-Path $SecretsFile) {
        $secrets = Get-Content $SecretsFile -Raw | ConvertFrom-Json
        $Password = $secrets.SmtpPassword
    }
} catch {
    Write-Warning "Could not load secrets file"
}

# Fallback to environment variable
if (!$Password) {
    $Password = $env:SMTP_PASSWORD
}

# If still no password, prompt (for manual runs)
if (!$Password) {
    Write-Error "SMTP password not found. Run credential-manager.ps1 to set it up."
    exit 1
}

$subject = "News Digest - $Date"

# Build HTML body
$htmlTemplate = @"
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
    <div style="background: #1e3c72; color: white; padding: 30px; text-align: center; border-radius: 12px 12px 0 0;">
        <h1 style="margin: 0;">📰 News Digest</h1>
        <p>$Date</p>
    </div>
    <div style="background: #f8f9fa; padding: 30px; border-radius: 0 0 12px 12px;">
        <p>Your daily news digest has been generated and pushed to GitHub.</p>
        <div style="background: white; padding: 20px; border-radius: 8px; text-align: center; margin: 20px 0;">
            <a href="$HtmlUrl" target="_blank" style="color: #667eea; text-decoration: none; font-size: 1.1em; font-weight: bold;">View Digest</a>
        </div>
        <p>The digest includes:</p>
        <ul>
            <li>Economic News</li>
            <li>Geopolitical News</li>
            <li>Daily Vocabulary Quiz</li>
        </ul>
    </div>
    <div style="text-align: center; color: #666; margin-top: 20px; font-size: 0.9em;">
        <p>Generated by XiaoYuZhou 🪐</p>
        <p><a href="https://github.com/zizaiqizi/newsDigestByXiaoYu">View on GitHub</a></p>
    </div>
</body>
</html>
"@

try {
    $message = New-Object System.Net.Mail.MailMessage
    $message.From = $From
    $message.To.Add($To)
    $message.Subject = $subject
    $message.Body = $htmlTemplate
    $message.IsBodyHtml = $true
    $message.BodyEncoding = [System.Text.Encoding]::UTF8
    $message.SubjectEncoding = [System.Text.Encoding]::UTF8
    
    $smtp = New-Object System.Net.Mail.SmtpClient
    $smtp.Host = $SmtpServer
    $smtp.Port = $SmtpPort
    $smtp.EnableSsl = $true
    $smtp.Credentials = New-Object System.Net.NetworkCredential($Username, $Password)
    
    $smtp.Send($message)
    Write-Host "✅ Email sent successfully to $To" -ForegroundColor Green
}
catch {
    Write-Error "Failed to send email: $($_.Exception.Message)"
    exit 1
}
